version: '3'
services:
  app:
    container_name: andrewbbs
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    env_file:
      - ./.envs/local/django/.env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
