version: '3'

volumes:
  postgres_data:

services:
  app:
    container_name: andrewbbs
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    env_file:
      - ./.envs/local/.env
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"

  postgres:
    container_name: andrewbbs-postgres
    image: postgres:15
    env_file:
      - ./.envs/local/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    
  pgamin:
    container_name: andrewbbs-pgadmin
    image: dpage/pgadmin4
    env_file:
      - ./.envs/local/.env
    ports:
      - "5050:80"