# Generated by Django 4.1.7 on 2023-05-14 21:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("andrewbbs", "0005_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
