# Generated by Django 4.1.7 on 2023-05-15 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("andrewbbs", "0006_message_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
