# Generated by Django 3.2.9 on 2021-12-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andrewbbs', '0002_auto_20211125_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='codes',
            field=models.ManyToManyField(blank=True, to='andrewbbs.AccessCode'),
        ),
    ]
