# Generated by Django 4.1.7 on 2023-03-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("andrewbbs", "0003_alter_member_unlocked_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="unlocked_codes",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
