# Generated by Django 3.2.9 on 2021-12-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('andrewbbs', '0003_alter_screen_codes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesscode',
            old_name='valid',
            new_name='enabled',
        ),
    ]
