# Generated by Django 4.1.7 on 2023-03-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("andrewbbs", "0004_rename_valid_accesscode_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screen",
            name="codes",
            field=models.ManyToManyField(
                blank=True, related_name="screens", to="andrewbbs.accesscode"
            ),
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("handle", models.CharField(max_length=100, unique=True)),
                ("phone", models.CharField(max_length=100, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("zip", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unlocked_codes",
                    models.ManyToManyField(
                        blank=True, related_name="members", to="andrewbbs.accesscode"
                    ),
                ),
            ],
            options={
                "ordering": ["handle"],
            },
        ),
    ]
