# Generated by Django 4.1.7 on 2023-03-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("andrewbbs", "0005_alter_screen_codes_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="unlocked_codes",
        ),
        migrations.AddField(
            model_name="member",
            name="unlocked_codes",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
