# Generated by Django 4.1.7 on 2023-03-10 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("andrewbbs", "0006_remove_member_unlocked_codes_member_unlocked_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="phone",
            field=models.CharField(
                max_length=17,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Please enter a valid phone number.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
