# Generated by Django 4.1.7 on 2023-03-12 05:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("andrewbbs", "0007_alter_member_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True
            ),
        ),
    ]
