# Generated by Django 4.1.7 on 2023-03-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("andrewbbs", "0009_member_last_login_member_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="member",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
