name: Run CI

on:
  push:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Environments
        run: cp ./.envs/local/.env.example .env

      - name: Display local .env
        run: cat .env

      - name: Build App 
        run: make build

      - name: Run Tests
        run: make test
